name: Bicep Azure Deployment
trigger:
- main

variables:

  resourceGroupName: 'Test'
  location: 'UkWest'
  azureSubscription: 'ConnMorrison'
  resourcePrefix: 'cjm'

 

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2  
      displayName: 'build bicep artifact' 
      inputs: 
        azureSubscription: $(azureSubscription) 
        scriptType: 'pscore'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file main.bicep'  

    - task: PublishBuildArtifacts@1 
      displayName: 'Publish artifact in pipeline' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/main.json'  
        ArtifactName: 'finishedTemplate'  
        publishLocation: 'Container' 

- stage: deploy
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy bicep to Azure'
    environment: 'AzureDeployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name $(ResourceGroupName) --location $(location)
                az deployment group create  `
                --template-file $(Build.SourcesDirectory)/ResourceGroup/ResourceGroup.bicep `
