name: CI
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@main
      with:
        scope: subscription
        subscriptionId: 36488cb1-7df3-42aa-b050-30d1dc788dce
        region: UK West
        template: ./ResourceGroup/ResourceGroup.bicep


   - name: Deploy virtual network
      uses: azure/arm-deploy@main
      with:
        scope: subscription
        subscriptionId: 36488cb1-7df3-42aa-b050-30d1dc788dce
        region: Uk West
        template: ./Network/DeployNetwork.bicep
        #testingwithconnmorr